### PR TITLE
Fix issue 1: Remove folders in results, grab top results from refinedResults

### LINKED ISSUE #1: Skater treats folders as bookmarks
Way to reproduce:
1. Create a new bookmark
2. Store that bookmark in a newly created folder, call it `Test` 
3. Search for `Test` or `test`
4. Press Enter (sometimes takes you to random bookmark) _or_ click the link (results in an error)

Fix:
Skater should filter out bookmark folders, there may be a detail about this in the bookmark object, such as a blank URL property.

### PR DESCRIPTION
**Pull request by Ecalzo**
fixes #1  
* Removes folders from results by checking if a result object has a `'url'` property
* Fixes bug where top result was grabbed from unfiltered results list

### CODE REVIEW

File: popup.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ function refineResults(searchResults, query) {
     const queryLen = query.length;
     const queryLower = query.toLowerCase();
```
Comment (edwinyung) [inline popup.js:33]: both variable definition lines are unnecessarily verbose since you're only using these once. Just call them on query below

File: popup.js [hunk 2]
```diff
@@ -19,7 +19,7 @@ document.addEventListener('DOMContentLoaded', function() {
     updateLinkEventListeners();
     if (event.key === "Enter") {
       // go to first event in the list
-      const top_result = searchResults[0];
+      const top_result = refinedResults[0];
```
Comment (edwinyung) [inline popup.js:22]: not necessary to make a new variable since you already have the comment above

**Review by edwinyung — APPROVED** [review]
good job

File: popup.js [hunk 3]
```diff
@@ -32,7 +32,7 @@ function refineResults(searchResults, query) {
     const queryLen = query.length;
     const queryLower = query.toLowerCase();
     const bookmarkTitle = result.title.substring(0, queryLen).toLowerCase();
-    return bookmarkTitle.includes(queryLower);
+    return bookmarkTitle.includes(queryLower) & result.hasOwnProperty('url');
```
Comment (wojm) [inline popup.js:35]:
```
return searchResults.filter(result => result.title.startsWith(query) && result.url);
```
